# Generated by Django 2.1.5 on 2019-01-31 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 31, 12, 50, 53, 782117), verbose_name='Date publised'),
        ),
    ]
