# Generated by Django 2.1.5 on 2019-02-02 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190202_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='tutorial_summary',
            new_name='series_summary',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 2, 19, 42, 3, 35453), verbose_name='Date publised'),
        ),
    ]
