# Generated by Django 2.1.5 on 2019-02-02 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190202_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 2, 21, 6, 26, 721389), verbose_name='Date publised'),
        ),
    ]
