# Generated by Django 2.1.5 on 2019-02-02 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190202_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='cateory_sammary',
            new_name='cateory_summary',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 2, 21, 6, 34, 249478), verbose_name='Date publised'),
        ),
    ]
